
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend

    env_file:
      - app/.env
    command: >
      sh -c "
      if ! alembic current 2>/dev/null; then
          echo '🆕 No migrations detected, autogenerating initial revision...';
          alembic revision --autogenerate -m 'init';
      fi;
      alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8010
      "

    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8010:8010"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - spy-net


  db:
    image: postgres:17
    env_file:
      - app/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - spy-net


volumes:
  postgres_data:
  static_volume:

networks:
  spy-net:
    driver: bridge